version: "3"

vars:
  VERSION:
    sh: grep '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/'

tasks:
  bump:patch:
    cmds:
      - |
        CURRENT_VERSION={{.VERSION}}
        NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1 "." $2 "." $3 + 1}')
        python3 -c "import re; f=open('pyproject.toml','r'); c=f.read(); f.close(); c=re.sub(r'^version = \".*\"', 'version = \"$NEW_VERSION\"', c, flags=re.MULTILINE); f=open('pyproject.toml','w'); f.write(c); f.close()"
        python3 -c "import re; f=open('src/pytest_autofocus/__init__.py','r'); c=f.read(); f.close(); c=re.sub(r'^__version__ = \".*\"', '__version__ = \"$NEW_VERSION\"', c, flags=re.MULTILINE); f=open('src/pytest_autofocus/__init__.py','w'); f.write(c); f.close()"
        echo "Bumped version from $CURRENT_VERSION to $NEW_VERSION"
  clean:
    cmds:
      - rm -rf dist/ build/
      - find . -type d -name "*.egg-info" -exec rm -rf {} + 2>/dev/null || true
  build:
    deps: [clean]
    cmds:
      - uv run python -m build
  publish:
    deps: [bump:patch, build]
    cmds:
      - uv run twine upload dist/*
  release:
    cmds:
      - git tag -a v{{.VERSION}} -m "Release v{{.VERSION}}"
      - git push --follow-tags origin main